<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('categories')->delete();
        
        \DB::table('categories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Fruits & Vegetables',
                'slug' => 'fruits-vegetables',
                'icon' => 'FruitsVegetable',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 00:21:31',
                'updated_at' => '2021-03-08 00:21:31',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Fruits',
                'slug' => 'fruits',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 1,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 00:22:04',
                'updated_at' => '2021-03-08 00:22:04',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Vegetables',
                'slug' => 'vegetables',
                'icon' => NULL,
                'description' => NULL,
                'image' => '{"id": null, "original": null, "thumbnail": null}',
                'details' => NULL,
                'parent' => 1,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 00:57:48',
                'updated_at' => '2021-03-09 04:51:24',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Meat & Fish',
                'slug' => 'meat-fish',
                'icon' => 'MeatFish',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 01:54:16',
                'updated_at' => '2021-03-08 01:54:16',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Fresh Fish',
                'slug' => 'fresh-fish',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 4,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 01:54:47',
                'updated_at' => '2021-03-08 01:54:47',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Meat',
                'slug' => 'meat',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 4,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 01:55:14',
                'updated_at' => '2021-03-08 01:55:14',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Snacks',
                'slug' => 'snacks',
                'icon' => 'Snacks',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 01:55:56',
                'updated_at' => '2021-03-08 01:55:56',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Nuts & Biscuits',
                'slug' => 'nuts-biscuits',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 7,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 01:57:28',
                'updated_at' => '2021-03-08 01:57:28',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Chocolates',
                'slug' => 'chocolates',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 7,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 01:58:44',
                'updated_at' => '2021-03-08 01:58:44',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Crisps',
                'slug' => 'crisps',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 7,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 01:59:05',
                'updated_at' => '2021-03-08 01:59:05',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Noodles & Pasta',
                'slug' => 'noodles-pasta',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 7,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 01:59:23',
                'updated_at' => '2021-03-08 01:59:23',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Sauce',
                'slug' => 'sauce',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 7,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:00:00',
                'updated_at' => '2021-03-08 02:00:00',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Pet Care',
                'slug' => 'pet-care',
                'icon' => 'PetCare',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:47:41',
                'updated_at' => '2021-03-08 02:47:41',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Soup',
                'slug' => 'soup',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 7,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:48:49',
                'updated_at' => '2021-03-08 02:48:49',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Cat Food',
                'slug' => 'cat-food',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 13,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:49:17',
                'updated_at' => '2021-03-08 02:49:17',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Dog Food',
                'slug' => 'dog-food',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 13,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:49:51',
                'updated_at' => '2021-03-08 02:49:51',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Accessories',
                'slug' => 'accessories',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 13,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:50:51',
                'updated_at' => '2021-03-08 02:50:51',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Home & Cleaning',
                'slug' => 'home-cleaning',
                'icon' => 'HomeCleaning',
                'description' => NULL,
                'image' => '{"id": null, "original": null, "thumbnail": null}',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:51:38',
                'updated_at' => '2021-03-08 02:52:52',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Air Freshner',
                'slug' => 'air-freshner',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 18,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:52:00',
                'updated_at' => '2021-03-08 02:52:00',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Cleaning Products',
                'slug' => 'cleaning-products',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 18,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:52:27',
                'updated_at' => '2021-03-08 02:52:27',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Kitchen Accessories',
                'slug' => 'kitchen-accessories',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 18,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:53:56',
                'updated_at' => '2021-03-08 02:53:56',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Laundry',
                'slug' => 'laundry',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 18,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:55:12',
                'updated_at' => '2021-03-08 02:55:12',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Dairy',
                'slug' => 'dairy',
                'icon' => 'Dairy',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:55:58',
                'updated_at' => '2021-03-08 02:55:58',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Milk',
                'slug' => 'milk',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 23,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:58:35',
                'updated_at' => '2021-03-08 02:58:35',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Butter',
                'slug' => 'butter',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 23,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:58:51',
                'updated_at' => '2021-03-08 02:58:51',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Egg',
                'slug' => 'egg',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 23,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:59:05',
                'updated_at' => '2021-03-08 02:59:05',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Yogurt',
                'slug' => 'yogurt',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 23,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 02:59:27',
                'updated_at' => '2021-03-08 02:59:27',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Cooking',
                'slug' => 'cooking',
                'icon' => 'Cooking',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:00:05',
                'updated_at' => '2021-03-08 03:00:05',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Oil',
                'slug' => 'oil',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 28,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:05:28',
                'updated_at' => '2021-03-08 03:05:28',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Rice',
                'slug' => 'rice',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 28,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:05:47',
                'updated_at' => '2021-03-08 03:05:47',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Salt & Sugar',
                'slug' => 'salt-sugar',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 28,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:06:20',
                'updated_at' => '2021-03-08 03:06:20',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Spices',
                'slug' => 'spices',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 28,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:06:39',
                'updated_at' => '2021-03-08 03:06:39',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Breakfast',
                'slug' => 'breakfast',
                'icon' => 'Breakfast',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:07:13',
                'updated_at' => '2021-03-08 03:07:13',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Bread',
                'slug' => 'bread',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 33,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:07:35',
                'updated_at' => '2021-03-08 03:07:35',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Cereal',
                'slug' => 'cereal',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 33,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:07:57',
                'updated_at' => '2021-03-08 03:07:57',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Jam',
                'slug' => 'jam',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 33,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:08:19',
                'updated_at' => '2021-03-08 03:08:19',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Beverage',
                'slug' => 'beverage',
                'icon' => 'Beverage',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:08:59',
                'updated_at' => '2021-03-08 03:08:59',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Coffee',
                'slug' => 'coffee',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 37,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:09:22',
                'updated_at' => '2021-03-08 03:09:22',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Energy Drinks',
                'slug' => 'energy-drinks',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 37,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:09:38',
                'updated_at' => '2021-03-08 03:09:38',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Juice',
                'slug' => 'juice',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 37,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:09:53',
                'updated_at' => '2021-03-08 03:09:53',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Fizzy Drinks',
                'slug' => 'fizzy-drinks',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 37,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:10:10',
                'updated_at' => '2021-03-08 03:10:10',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Tea',
                'slug' => 'tea',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 37,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:10:25',
                'updated_at' => '2021-03-08 03:10:25',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Health & Beauty',
                'slug' => 'health-beauty',
                'icon' => 'BeautyHealth',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:11:08',
                'updated_at' => '2021-03-08 03:11:08',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Bath',
                'slug' => 'bath',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 43,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:11:28',
                'updated_at' => '2021-03-08 03:11:28',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Cream',
                'slug' => 'cream',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 43,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:11:58',
                'updated_at' => '2021-03-08 03:11:58',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Deodorant',
                'slug' => 'deodorant',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 43,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:12:18',
                'updated_at' => '2021-03-08 03:12:18',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Face Care',
                'slug' => 'face-care',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 43,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:12:32',
                'updated_at' => '2021-03-08 03:12:32',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Oral Care',
                'slug' => 'oral-care',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 43,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:12:45',
                'updated_at' => '2021-03-08 03:12:45',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Shaving Needs',
                'slug' => 'shaving-needs',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 43,
                'type_id' => 1,
                'status' => 1,
                'created_at' => '2021-03-08 03:12:59',
                'updated_at' => '2021-03-08 03:12:59',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Face',
                'slug' => 'face',
                'icon' => 'Face',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 22:45:12',
                'updated_at' => '2021-03-08 22:45:12',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Blusher',
                'slug' => 'blusher',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 50,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 22:45:43',
                'updated_at' => '2021-03-08 22:45:43',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Foundation',
                'slug' => 'foundation',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 50,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 22:46:02',
                'updated_at' => '2021-03-08 22:46:02',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Face Powder',
                'slug' => 'face-powder',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 50,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 22:46:24',
                'updated_at' => '2021-03-08 22:46:24',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Eyes',
                'slug' => 'eyes',
                'icon' => 'Eyes',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 22:46:51',
                'updated_at' => '2021-03-08 22:46:51',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Eye Shadow',
                'slug' => 'eye-shadow',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 54,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 22:47:10',
                'updated_at' => '2021-03-08 22:47:10',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Glitter',
                'slug' => 'glitter',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 54,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 22:47:28',
                'updated_at' => '2021-03-08 22:47:28',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Mascara',
                'slug' => 'mascara',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 54,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 22:47:47',
                'updated_at' => '2021-03-08 22:47:47',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Lips',
                'slug' => 'lips',
                'icon' => 'Lips',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 22:48:13',
                'updated_at' => '2021-03-08 22:48:13',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Lip Gloss',
                'slug' => 'lip-liner',
                'icon' => NULL,
                'description' => NULL,
                'image' => '{"id": null, "original": null, "thumbnail": null}',
                'details' => NULL,
                'parent' => 58,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 22:48:28',
                'updated_at' => '2021-03-08 22:48:58',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Lip Stick',
                'slug' => 'lip-stick',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 58,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 22:49:35',
                'updated_at' => '2021-03-08 22:49:35',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Lip Kit',
                'slug' => 'lip-kit',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 58,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 22:49:49',
                'updated_at' => '2021-03-08 22:49:49',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Accessories',
                'slug' => 'accessories-1',
                'icon' => 'Accessories',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 23:02:05',
                'updated_at' => '2021-03-08 23:02:05',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Shaving Needs',
                'slug' => 'shaving-needs-1',
                'icon' => 'ShavingNeeds',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 23:02:24',
                'updated_at' => '2021-03-08 23:02:24',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'Oral Care',
                'slug' => 'oral-care-1',
                'icon' => 'OralCare',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 23:02:47',
                'updated_at' => '2021-03-08 23:02:47',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'Facial Care',
                'slug' => 'facial-care',
                'icon' => 'FacialCare',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 23:03:15',
                'updated_at' => '2021-03-08 23:03:15',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'Deodorant',
                'slug' => 'deodorant-1',
                'icon' => 'Deodorant',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 23:03:30',
                'updated_at' => '2021-03-08 23:03:30',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'Bath & Oil',
                'slug' => 'bath-oil',
                'icon' => 'BathOil',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 3,
                'status' => 1,
                'created_at' => '2021-03-08 23:03:46',
                'updated_at' => '2021-03-08 23:03:46',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'Women Dress',
                'slug' => 'women-dress',
                'icon' => 'WomenDress',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-08 23:25:14',
                'updated_at' => '2021-03-08 23:25:14',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'Printed',
                'slug' => 'printed',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 68,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-08 23:26:10',
                'updated_at' => '2021-03-08 23:26:10',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'Floral',
                'slug' => 'floral',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 68,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-08 23:26:52',
                'updated_at' => '2021-03-08 23:26:52',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'Single Color',
                'slug' => 'single-color',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 68,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-08 23:27:12',
                'updated_at' => '2021-03-08 23:27:12',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'Outer Wear',
                'slug' => 'outer-wear',
                'icon' => 'OuterWear',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-09 01:55:55',
                'updated_at' => '2021-03-09 01:55:55',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'Hoodie',
                'slug' => 'hoodie',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 72,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-09 01:56:39',
                'updated_at' => '2021-03-09 01:56:39',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'Jacket',
                'slug' => 'jacket',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 72,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-09 01:56:55',
                'updated_at' => '2021-03-09 01:56:55',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'Blazer',
                'slug' => 'blazer',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 72,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-09 01:57:20',
                'updated_at' => '2021-03-09 01:57:20',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'Waist Coat',
                'slug' => 'waist-coat',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 72,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-09 01:57:40',
                'updated_at' => '2021-03-09 01:57:40',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'Pants',
                'slug' => 'pants',
                'icon' => 'Pants',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-09 01:58:22',
                'updated_at' => '2021-03-09 01:58:22',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'Jeans',
                'slug' => 'jeans',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 77,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-09 01:58:43',
                'updated_at' => '2021-03-09 01:58:43',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'Chinos',
                'slug' => 'chinos',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 77,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-09 01:58:57',
                'updated_at' => '2021-03-09 01:58:57',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'Sports',
                'slug' => 'sports',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 77,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-09 01:59:13',
                'updated_at' => '2021-03-09 01:59:13',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'Tops',
                'slug' => 'tops',
                'icon' => 'Tops',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-09 01:59:55',
                'updated_at' => '2021-03-09 01:59:55',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'Skirts',
                'slug' => 'skirts',
                'icon' => 'Skirts',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-09 02:01:43',
                'updated_at' => '2021-03-25 06:01:38',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'Shirts',
                'slug' => 'shirts',
                'icon' => 'Shirts',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 5,
                'status' => 1,
                'created_at' => '2021-03-09 02:02:05',
                'updated_at' => '2021-03-09 02:02:05',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'Purse',
                'slug' => 'purse',
                'icon' => 'Purse',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 4,
                'status' => 1,
                'created_at' => '2021-03-09 02:49:20',
                'updated_at' => '2021-03-09 02:49:20',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'Hand bags',
                'slug' => 'hand-bags',
                'icon' => 'HandBags',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 4,
                'status' => 1,
                'created_at' => '2021-03-09 02:49:50',
                'updated_at' => '2021-03-09 02:49:50',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'Shoulder bags',
                'slug' => 'shoulder-bags',
                'icon' => 'ShoulderBags',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 4,
                'status' => 1,
                'created_at' => '2021-03-09 02:50:10',
                'updated_at' => '2021-03-09 02:50:10',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'Wallet',
                'slug' => 'wallet',
                'icon' => 'Wallet',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 4,
                'status' => 1,
                'created_at' => '2021-03-09 02:50:29',
                'updated_at' => '2021-03-09 02:50:29',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'Laptop bags',
                'slug' => 'laptop-bags',
                'icon' => 'LaptopBags',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 4,
                'status' => 1,
                'created_at' => '2021-03-09 02:50:49',
                'updated_at' => '2021-03-09 02:50:49',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'Juice',
                'slug' => 'juice-1',
                'icon' => NULL,
                'description' => NULL,
                'image' => '{"id": "423", "original": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/422/Juice_q1dlke.png", "thumbnail": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/422/conversions/Juice_q1dlke-thumbnail.jpg"}',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 2,
                'status' => 1,
                'created_at' => '2021-03-13 07:34:33',
                'updated_at' => '2021-03-13 07:34:33',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'Coffee & Tea',
                'slug' => 'coffee-tea',
                'icon' => NULL,
                'description' => NULL,
                'image' => '{"id": "424", "original": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/423/Coffee_j6vccc.png", "thumbnail": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/423/conversions/Coffee_j6vccc-thumbnail.jpg"}',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 2,
                'status' => 1,
                'created_at' => '2021-03-13 07:36:15',
                'updated_at' => '2021-03-13 07:36:15',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'Cookies',
                'slug' => 'cookies',
                'icon' => NULL,
                'description' => NULL,
                'image' => '{"id": "425", "original": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/424/Cookies_ggshwp.png", "thumbnail": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/424/conversions/Cookies_ggshwp-thumbnail.jpg"}',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 2,
                'status' => 1,
                'created_at' => '2021-03-13 07:36:44',
                'updated_at' => '2021-03-13 07:36:44',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'Round Cake',
                'slug' => 'round-cake',
                'icon' => NULL,
                'description' => NULL,
                'image' => '{"id": "426", "original": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/425/Round-Cake_rfsrkr.png", "thumbnail": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/425/conversions/Round-Cake_rfsrkr-thumbnail.jpg"}',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 2,
                'status' => 1,
                'created_at' => '2021-03-13 07:37:05',
                'updated_at' => '2021-03-13 07:37:05',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'Pita Bread',
                'slug' => 'pita-bread',
                'icon' => NULL,
                'description' => NULL,
                'image' => '{"id": "427", "original": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/426/Pita-Bread_bvrwtn.png", "thumbnail": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/426/conversions/Pita-Bread_bvrwtn-thumbnail.jpg"}',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 2,
                'status' => 1,
                'created_at' => '2021-03-13 07:37:27',
                'updated_at' => '2021-03-13 07:37:27',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'Sliced Cake',
                'slug' => 'sliced-cake',
                'icon' => NULL,
                'description' => NULL,
                'image' => '{"id": "428", "original": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/427/Chees-Cake_whi1yd.png", "thumbnail": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/427/conversions/Chees-Cake_whi1yd-thumbnail.jpg"}',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 2,
                'status' => 1,
                'created_at' => '2021-03-13 07:37:59',
                'updated_at' => '2021-03-13 07:37:59',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'Muffin',
                'slug' => 'muffin',
                'icon' => NULL,
                'description' => NULL,
                'image' => '{"id": "429", "original": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/428/Muffin_yiuqcf.png", "thumbnail": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/428/conversions/Muffin_yiuqcf-thumbnail.jpg"}',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 2,
                'status' => 1,
                'created_at' => '2021-03-13 07:38:24',
                'updated_at' => '2021-03-13 07:38:24',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'Danish',
                'slug' => 'danish',
                'icon' => NULL,
                'description' => NULL,
                'image' => '{"id": "430", "original": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/429/Danish_ybcbuq.png", "thumbnail": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/429/conversions/Danish_ybcbuq-thumbnail.jpg"}',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 2,
                'status' => 1,
                'created_at' => '2021-03-13 07:38:56',
                'updated_at' => '2021-03-13 07:38:56',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'Croissants',
                'slug' => 'croissants',
                'icon' => NULL,
                'description' => NULL,
                'image' => '{"id": "431", "original": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/430/Croissant_nqjflw.png", "thumbnail": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/430/conversions/Croissant_nqjflw-thumbnail.jpg"}',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 2,
                'status' => 1,
                'created_at' => '2021-03-13 07:39:31',
                'updated_at' => '2021-03-13 07:39:31',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'Feeter & Pies',
                'slug' => 'feeter-pies',
                'icon' => NULL,
                'description' => NULL,
                'image' => '{"id": "432", "original": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/431/Feeter-pies_eidfxl.png", "thumbnail": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/431/conversions/Feeter-pies_eidfxl-thumbnail.jpg"}',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 2,
                'status' => 1,
                'created_at' => '2021-03-13 07:40:00',
                'updated_at' => '2021-03-13 07:40:00',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'Toast & Loaf',
                'slug' => 'toast-loaf',
                'icon' => NULL,
                'description' => NULL,
                'image' => '{"id": "433", "original": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/432/Toast_ufzuwx.png", "thumbnail": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/432/conversions/Toast_ufzuwx-thumbnail.jpg"}',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 2,
                'status' => 1,
                'created_at' => '2021-03-13 07:40:31',
                'updated_at' => '2021-03-13 07:40:31',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'Soft Bread',
                'slug' => 'soft-bread',
                'icon' => NULL,
                'description' => NULL,
                'image' => '{"id": "434", "original": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/433/SoftBread_a85vlg.png", "thumbnail": "https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/433/conversions/SoftBread_a85vlg-thumbnail.jpg"}',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 2,
                'status' => 1,
                'created_at' => '2021-03-13 07:40:58',
                'updated_at' => '2021-03-13 07:40:58',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'name' => 'Bed',
                'slug' => 'bed',
                'icon' => 'Bed',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:43:22',
                'updated_at' => '2021-03-13 07:43:22',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'name' => 'Master Bed',
                'slug' => 'master-bed',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 101,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:43:48',
                'updated_at' => '2021-03-13 07:43:48',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'name' => 'Single Bed',
                'slug' => 'single-bed',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 101,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:44:05',
                'updated_at' => '2021-03-13 07:44:05',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'name' => 'Semi Double Bed',
                'slug' => 'semi-double-bed',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 101,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:44:24',
                'updated_at' => '2021-03-13 07:44:24',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'name' => 'Chair',
                'slug' => 'chair',
                'icon' => 'Chair',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:44:51',
                'updated_at' => '2021-03-13 07:44:51',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'name' => 'Cozy Chair',
                'slug' => 'cozy-chair',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 105,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:45:07',
                'updated_at' => '2021-03-13 07:45:07',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'name' => 'Rocking Chair',
                'slug' => 'rocking-chair',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 105,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:45:49',
                'updated_at' => '2021-03-13 07:45:49',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'name' => 'Single Chair',
                'slug' => 'single-chair',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 105,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:46:11',
                'updated_at' => '2021-03-13 07:46:11',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'name' => 'Sofa',
                'slug' => 'sofa',
                'icon' => 'Sofa',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:46:43',
                'updated_at' => '2021-03-13 07:46:43',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'name' => 'Double Sofa',
                'slug' => 'double-sofa',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 109,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:47:04',
                'updated_at' => '2021-03-13 07:47:04',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'name' => 'Single Sofa',
                'slug' => 'single-sofa',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 109,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:47:22',
                'updated_at' => '2021-03-13 07:47:22',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'name' => 'Sofa Set',
                'slug' => 'sofa-set',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 109,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:47:40',
                'updated_at' => '2021-03-13 07:47:40',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'name' => 'Table',
                'slug' => 'table',
                'icon' => 'Table',
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:48:34',
                'updated_at' => '2021-03-13 07:48:34',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'name' => 'Bedside Table',
                'slug' => 'bedside-table',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 113,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:50:14',
                'updated_at' => '2021-03-13 07:50:14',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'name' => 'Coffee Table',
                'slug' => 'coffee-table',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 113,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:50:37',
                'updated_at' => '2021-03-13 07:50:37',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'name' => 'Dining Table',
                'slug' => 'dining-table',
                'icon' => NULL,
                'description' => NULL,
                'image' => '[]',
                'details' => NULL,
                'parent' => 113,
                'type_id' => 6,
                'status' => 1,
                'created_at' => '2021-03-13 07:50:59',
                'updated_at' => '2021-03-13 07:50:59',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'name' => 'Team Category 1',
                'slug' => NULL,
                'icon' => NULL,
            'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)',
                'image' => '632d3fc4a2dba1663909828.jpg',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => NULL,
                'status' => 1,
                'created_at' => '2022-09-22 22:10:28',
                'updated_at' => '2022-09-22 22:10:28',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'name' => 'Team Category 2',
                'slug' => NULL,
                'icon' => NULL,
            'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)',
                'image' => '632d4009802da1663909897.jpg',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => NULL,
                'status' => 1,
                'created_at' => '2022-09-22 22:11:37',
                'updated_at' => '2022-09-22 22:11:37',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'name' => 'Team Category 3',
                'slug' => NULL,
                'icon' => NULL,
            'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)',
                'image' => '632d401816f991663909912.jpg',
                'details' => NULL,
                'parent' => NULL,
                'type_id' => NULL,
                'status' => 1,
                'created_at' => '2022-09-22 22:11:52',
                'updated_at' => '2022-09-22 22:11:52',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}