<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'firstname' => 'Tran',
                'lastname' => 'Thuy',
                'username' => 'tranthanhbinhmathdephcm001',
                'email' => 'tranthanhbinhmathdephcm.001@gmail.com',
                'country_code' => 'VN',
                'is_active' => 1,
                'shop_id' => NULL,
                'email_notification_status' => 1,
                'push_notification_status' => 1,
                'device_type' => 1,
                'language' => NULL,
                'device_id' => NULL,
                'zip' => NULL,
                'state' => NULL,
                'city' => NULL,
                'reset_code' => NULL,
                'email_verified' => '1',
                'role' => 1,
                'photo' => NULL,
                'phone' => NULL,
                'country' => 'DS',
                'active_status' => 1,
                'name' => 'tranthanhbinhmathdephcm.001',
                'mobile' => '840936637595',
                'ref_by' => 0,
                'balance' => '64459.00000000',
                'password' => '$2y$10$ntkFcfElzbOetDxoqpcoX.QErAzHh3w.jjg5wdLVjxkPiOixggPH.',
                'image' => '62f84b7ec746c1660439422.png',
                'email_verified_at' => NULL,
                'address' => '{"address":"63 Vo Van Tan","state":"HCMC","zip":"700000","country":"Vietnam","city":"HCMC"}',
                'status' => 1,
                'ev' => 1,
                'sv' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-08-11 15:42:58',
                'updated_at' => '2022-09-25 07:39:46',
            ),
            1 => 
            array (
                'id' => 2,
                'firstname' => 'Tran',
                'lastname' => 'Thuy',
                'username' => 'tranthanhbinhmathdephcm002',
                'email' => 'tranthanhbinhmathdephcm.002@gmail.com',
                'country_code' => 'AF',
                'is_active' => 1,
                'shop_id' => NULL,
                'email_notification_status' => 1,
                'push_notification_status' => 1,
                'device_type' => 1,
                'language' => NULL,
                'device_id' => NULL,
                'zip' => NULL,
                'state' => NULL,
                'city' => NULL,
                'reset_code' => NULL,
                'email_verified' => '1',
                'role' => 2,
                'photo' => NULL,
                'phone' => NULL,
                'country' => 'AF',
                'active_status' => 1,
                'name' => 'tranthanhbinhmathdephcm.002',
                'mobile' => '930936637594',
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$3IDQB2LX3OdtIHNrXI89AOV1EbwW8.hUoydmXRfml0JLe4ypIodku',
                'image' => '62f524064be621660232710.png',
                'email_verified_at' => NULL,
                'address' => '{"address":"10 Vo Van Tan","state":"HCMC","zip":"70000","country":"Afghanistan","city":"HCMC"}',
                'status' => 1,
                'ev' => 1,
                'sv' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-08-11 15:44:03',
                'updated_at' => '2022-09-25 07:29:35',
            ),
            2 => 
            array (
                'id' => 3,
                'firstname' => 'Thuy',
                'lastname' => 'Tran Thanh',
                'username' => 'tommy.001',
                'email' => 'thuy.tranthanh.bd@gmail.com',
                'country_code' => 'VN',
                'is_active' => 1,
                'shop_id' => NULL,
                'email_notification_status' => 1,
                'push_notification_status' => 1,
                'device_type' => 1,
                'language' => NULL,
                'device_id' => NULL,
                'zip' => NULL,
                'state' => NULL,
                'city' => NULL,
                'reset_code' => NULL,
                'email_verified' => '0',
                'role' => 2,
                'photo' => NULL,
                'phone' => NULL,
                'country' => NULL,
                'active_status' => 1,
                'name' => 'Store Owner',
                'mobile' => '0936637594',
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$YcO21.ddXuoiA.8AD5X1OOxfjmBHkl45Vg58pAdMQ3sZ/bjkpXYZK',
                'image' => NULL,
                'email_verified_at' => NULL,
                'address' => '{"address":"86 Duong Dinh Hoi","city":"HCMC","state":"HCMV","zip":"70000","country":"Vietnam"}',
                'status' => 1,
                'ev' => 1,
                'sv' => 0,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'remember_token' => NULL,
                'created_at' => '2021-06-26 21:13:00',
                'updated_at' => '2022-10-01 01:56:25',
            ),
            3 => 
            array (
                'id' => 4,
                'firstname' => 'Thuy',
                'lastname' => 'Tran Thanh',
                'username' => 'tommy.002',
                'email' => 'admin@admin.com',
                'country_code' => 'VN',
                'is_active' => 1,
                'shop_id' => NULL,
                'email_notification_status' => 1,
                'push_notification_status' => 1,
                'device_type' => 1,
                'language' => NULL,
                'device_id' => NULL,
                'zip' => NULL,
                'state' => NULL,
                'city' => NULL,
                'reset_code' => NULL,
                'email_verified' => '0',
                'role' => 2,
                'photo' => NULL,
                'phone' => NULL,
                'country' => NULL,
                'active_status' => 1,
                'name' => 'admin',
                'mobile' => '0936637595',
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$cQmOB6pCp8g.FNVRJVUI.eM9k6HE4sP4VzlP5RVuRvYJvmBguEfi6',
                'image' => NULL,
                'email_verified_at' => NULL,
                'address' => '{"address":"86 Duong Dinh Hoi","city":"HCMC","state":"HCMV","zip":"70000","country":"Vietnam"}',
                'status' => 1,
                'ev' => 0,
                'sv' => 0,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'remember_token' => NULL,
                'created_at' => '2022-09-28 18:27:30',
                'updated_at' => '2022-10-01 01:55:17',
            ),
        ));
        
        
    }
}