<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class VariationOptionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('variation_options')->delete();
        
        \DB::table('variation_options')->insert(array (
            0 => 
            array (
                'id' => 157,
                'title' => 'Red/S',
                'price' => '30',
                'sale_price' => '20',
                'quantity' => '100',
                'is_disable' => 0,
                'sku' => '10010',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 173,
                'created_at' => '2021-05-09 10:47:03',
                'updated_at' => '2021-05-09 10:47:03',
            ),
            1 => 
            array (
                'id' => 158,
                'title' => 'Red/M',
                'price' => '30',
                'sale_price' => '20',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10011',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 173,
                'created_at' => '2021-05-09 10:47:03',
                'updated_at' => '2021-05-09 10:47:03',
            ),
            2 => 
            array (
                'id' => 159,
                'title' => 'Blue/S',
                'price' => '30',
                'sale_price' => '20',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10012',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 173,
                'created_at' => '2021-05-09 10:47:03',
                'updated_at' => '2021-05-09 10:47:03',
            ),
            3 => 
            array (
                'id' => 160,
                'title' => 'Blue/M',
                'price' => '30',
                'sale_price' => '20',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10013',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 173,
                'created_at' => '2021-05-09 10:47:03',
                'updated_at' => '2021-05-09 10:47:03',
            ),
            4 => 
            array (
                'id' => 161,
                'title' => 'Red/S',
                'price' => '40',
                'sale_price' => NULL,
                'quantity' => '100',
                'is_disable' => 0,
                'sku' => '10014',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 174,
                'created_at' => '2021-05-09 10:47:53',
                'updated_at' => '2021-05-10 02:06:23',
            ),
            5 => 
            array (
                'id' => 162,
                'title' => 'Red/M',
                'price' => '40',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10015',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 174,
                'created_at' => '2021-05-09 10:47:53',
                'updated_at' => '2021-05-10 02:06:23',
            ),
            6 => 
            array (
                'id' => 163,
                'title' => 'White/S',
                'price' => '40',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10016',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "S"}]',
                'product_id' => 174,
                'created_at' => '2021-05-09 10:47:53',
                'updated_at' => '2021-05-10 02:06:23',
            ),
            7 => 
            array (
                'id' => 164,
                'title' => 'White/M',
                'price' => '40',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10017',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "M"}]',
                'product_id' => 174,
                'created_at' => '2021-05-09 10:47:53',
                'updated_at' => '2021-05-10 02:06:24',
            ),
            8 => 
            array (
                'id' => 165,
                'title' => 'Blue/L',
                'price' => '50',
                'sale_price' => '40',
                'quantity' => '100',
                'is_disable' => 0,
                'sku' => '10018',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "L"}]',
                'product_id' => 175,
                'created_at' => '2021-05-09 10:48:58',
                'updated_at' => '2021-05-10 02:06:05',
            ),
            9 => 
            array (
                'id' => 166,
                'title' => 'Blue/M',
                'price' => '50',
                'sale_price' => '40',
                'quantity' => '100',
                'is_disable' => 0,
                'sku' => '10019',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 175,
                'created_at' => '2021-05-09 10:48:58',
                'updated_at' => '2021-05-10 02:06:05',
            ),
            10 => 
            array (
                'id' => 167,
                'title' => 'White/L',
                'price' => '50',
                'sale_price' => '40',
                'quantity' => '100',
                'is_disable' => 0,
                'sku' => '10020',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "L"}]',
                'product_id' => 175,
                'created_at' => '2021-05-09 10:48:58',
                'updated_at' => '2021-05-10 02:06:05',
            ),
            11 => 
            array (
                'id' => 168,
                'title' => 'White/M',
                'price' => '50',
                'sale_price' => '40',
                'quantity' => '100',
                'is_disable' => 0,
                'sku' => '10021',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "M"}]',
                'product_id' => 175,
                'created_at' => '2021-05-09 10:48:58',
                'updated_at' => '2021-05-10 02:06:05',
            ),
            12 => 
            array (
                'id' => 169,
                'title' => 'Red/M',
                'price' => '60',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10025',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 176,
                'created_at' => '2021-05-09 10:49:49',
                'updated_at' => '2021-05-10 02:05:57',
            ),
            13 => 
            array (
                'id' => 170,
                'title' => 'Red/XL',
                'price' => '60',
                'sale_price' => '50',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10026',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 176,
                'created_at' => '2021-05-09 10:49:49',
                'updated_at' => '2021-05-10 02:05:57',
            ),
            14 => 
            array (
                'id' => 171,
                'title' => 'Blue/M',
                'price' => '60',
                'sale_price' => '50',
                'quantity' => '50',
                'is_disable' => 0,
                'sku' => '10027',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 176,
                'created_at' => '2021-05-09 10:49:49',
                'updated_at' => '2021-05-10 02:05:57',
            ),
            15 => 
            array (
                'id' => 172,
                'title' => 'Blue/XL',
                'price' => '60',
                'sale_price' => '50',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10028',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 176,
                'created_at' => '2021-05-09 10:49:49',
                'updated_at' => '2021-05-10 02:05:57',
            ),
            16 => 
            array (
                'id' => 173,
                'title' => 'Blue/S',
                'price' => '30',
                'sale_price' => NULL,
                'quantity' => '300',
                'is_disable' => 0,
                'sku' => '10030',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 177,
                'created_at' => '2021-05-09 10:50:31',
                'updated_at' => '2021-05-10 02:05:49',
            ),
            17 => 
            array (
                'id' => 174,
                'title' => 'Blue/M',
                'price' => '30',
                'sale_price' => NULL,
                'quantity' => '300',
                'is_disable' => 0,
                'sku' => '10030',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 177,
                'created_at' => '2021-05-09 10:50:31',
                'updated_at' => '2021-05-10 02:05:49',
            ),
            18 => 
            array (
                'id' => 175,
                'title' => 'White/S',
                'price' => '30',
                'sale_price' => NULL,
                'quantity' => '300',
                'is_disable' => 0,
                'sku' => '10030',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "S"}]',
                'product_id' => 177,
                'created_at' => '2021-05-09 10:50:31',
                'updated_at' => '2021-05-10 02:05:49',
            ),
            19 => 
            array (
                'id' => 176,
                'title' => 'White/M',
                'price' => '30',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10030',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "M"}]',
                'product_id' => 177,
                'created_at' => '2021-05-09 10:50:31',
                'updated_at' => '2021-05-10 02:05:49',
            ),
            20 => 
            array (
                'id' => 177,
                'title' => 'Red/S',
                'price' => '40',
                'sale_price' => NULL,
                'quantity' => '400',
                'is_disable' => 0,
                'sku' => '10040',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 178,
                'created_at' => '2021-05-09 10:51:40',
                'updated_at' => '2021-05-10 02:05:42',
            ),
            21 => 
            array (
                'id' => 178,
                'title' => 'Red/M',
                'price' => '40',
                'sale_price' => NULL,
                'quantity' => '400',
                'is_disable' => 0,
                'sku' => '10049',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 178,
                'created_at' => '2021-05-09 10:51:40',
                'updated_at' => '2021-05-10 02:05:42',
            ),
            22 => 
            array (
                'id' => 179,
                'title' => 'Red/L',
                'price' => '40',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10041',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "L"}]',
                'product_id' => 178,
                'created_at' => '2021-05-09 10:51:40',
                'updated_at' => '2021-05-10 02:05:42',
            ),
            23 => 
            array (
                'id' => 180,
                'title' => 'Blue/S',
                'price' => '40',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10042',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 178,
                'created_at' => '2021-05-09 10:51:40',
                'updated_at' => '2021-05-10 02:05:42',
            ),
            24 => 
            array (
                'id' => 181,
                'title' => 'Blue/M',
                'price' => '40',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10044',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 178,
                'created_at' => '2021-05-09 10:51:40',
                'updated_at' => '2021-05-10 02:05:42',
            ),
            25 => 
            array (
                'id' => 182,
                'title' => 'Blue/L',
                'price' => '50',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10046',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "L"}]',
                'product_id' => 178,
                'created_at' => '2021-05-09 10:51:40',
                'updated_at' => '2021-05-10 02:05:42',
            ),
            26 => 
            array (
                'id' => 183,
                'title' => 'Red/XL',
                'price' => '30',
                'sale_price' => '25',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10050',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 179,
                'created_at' => '2021-05-09 10:52:27',
                'updated_at' => '2021-05-10 02:05:33',
            ),
            27 => 
            array (
                'id' => 184,
                'title' => 'Red/S',
                'price' => '30',
                'sale_price' => '25',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10051',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 179,
                'created_at' => '2021-05-09 10:52:27',
                'updated_at' => '2021-05-10 02:05:33',
            ),
            28 => 
            array (
                'id' => 185,
                'title' => 'Blue/XL',
                'price' => '30',
                'sale_price' => '25',
                'quantity' => '300',
                'is_disable' => 0,
                'sku' => '10052',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 179,
                'created_at' => '2021-05-09 10:52:27',
                'updated_at' => '2021-05-10 02:05:33',
            ),
            29 => 
            array (
                'id' => 186,
                'title' => 'Blue/S',
                'price' => '30',
                'sale_price' => '25',
                'quantity' => '300',
                'is_disable' => 0,
                'sku' => '10053',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 179,
                'created_at' => '2021-05-09 10:52:27',
                'updated_at' => '2021-05-10 02:05:33',
            ),
            30 => 
            array (
                'id' => 187,
                'title' => 'Red/M',
                'price' => '100',
                'sale_price' => '80',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10060',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 180,
                'created_at' => '2021-05-09 10:53:31',
                'updated_at' => '2021-05-10 02:04:37',
            ),
            31 => 
            array (
                'id' => 188,
                'title' => 'Red/L',
                'price' => '100',
                'sale_price' => '80',
                'quantity' => '210',
                'is_disable' => 0,
                'sku' => '10061',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "L"}]',
                'product_id' => 180,
                'created_at' => '2021-05-09 10:53:31',
                'updated_at' => '2021-05-10 02:04:37',
            ),
            32 => 
            array (
                'id' => 189,
                'title' => 'Blue/M',
                'price' => '100',
                'sale_price' => '80',
                'quantity' => '250',
                'is_disable' => 0,
                'sku' => '10062',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 180,
                'created_at' => '2021-05-09 10:53:31',
                'updated_at' => '2021-05-10 02:04:37',
            ),
            33 => 
            array (
                'id' => 190,
                'title' => 'Blue/L',
                'price' => '100',
                'sale_price' => '80',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10063',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "L"}]',
                'product_id' => 180,
                'created_at' => '2021-05-09 10:53:31',
                'updated_at' => '2021-05-10 02:04:37',
            ),
            34 => 
            array (
                'id' => 191,
                'title' => 'White/M',
                'price' => '100',
                'sale_price' => '80',
                'quantity' => '230',
                'is_disable' => 0,
                'sku' => '10065',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "M"}]',
                'product_id' => 180,
                'created_at' => '2021-05-09 10:53:31',
                'updated_at' => '2021-05-10 02:04:37',
            ),
            35 => 
            array (
                'id' => 192,
                'title' => 'White/L',
                'price' => '100',
                'sale_price' => '80',
                'quantity' => '600',
                'is_disable' => 0,
                'sku' => '10066',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "L"}]',
                'product_id' => 180,
                'created_at' => '2021-05-09 10:53:31',
                'updated_at' => '2021-05-10 02:04:37',
            ),
            36 => 
            array (
                'id' => 193,
                'title' => 'Red/S',
                'price' => '50',
                'sale_price' => NULL,
                'quantity' => '700',
                'is_disable' => 0,
                'sku' => '10070',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 541,
                'created_at' => '2021-05-09 10:54:17',
                'updated_at' => '2021-05-10 02:04:29',
            ),
            37 => 
            array (
                'id' => 194,
                'title' => 'Red/M',
                'price' => '50',
                'sale_price' => NULL,
                'quantity' => '600',
                'is_disable' => 0,
                'sku' => '10071',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 541,
                'created_at' => '2021-05-09 10:54:17',
                'updated_at' => '2021-05-10 02:04:29',
            ),
            38 => 
            array (
                'id' => 195,
                'title' => 'Blue/S',
                'price' => '50',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10072',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 541,
                'created_at' => '2021-05-09 10:54:17',
                'updated_at' => '2021-05-10 02:04:29',
            ),
            39 => 
            array (
                'id' => 196,
                'title' => 'Blue/M',
                'price' => '50',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10073',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 541,
                'created_at' => '2021-05-09 10:54:17',
                'updated_at' => '2021-05-10 02:04:29',
            ),
            40 => 
            array (
                'id' => 197,
                'title' => 'Red/S',
                'price' => '30',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10100',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 163,
                'created_at' => '2021-05-09 11:10:11',
                'updated_at' => '2021-05-10 02:08:36',
            ),
            41 => 
            array (
                'id' => 198,
                'title' => 'Red/M',
                'price' => '30',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10101',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 163,
                'created_at' => '2021-05-09 11:10:11',
                'updated_at' => '2021-05-10 02:08:36',
            ),
            42 => 
            array (
                'id' => 199,
                'title' => 'Blue/S',
                'price' => '30',
                'sale_price' => NULL,
                'quantity' => '30',
                'is_disable' => 0,
                'sku' => '10102',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 163,
                'created_at' => '2021-05-09 11:10:11',
                'updated_at' => '2021-05-10 02:08:36',
            ),
            43 => 
            array (
                'id' => 200,
                'title' => 'Blue/M',
                'price' => '30',
                'sale_price' => NULL,
                'quantity' => '300',
                'is_disable' => 0,
                'sku' => '10103',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 163,
                'created_at' => '2021-05-09 11:10:11',
                'updated_at' => '2021-05-10 02:08:36',
            ),
            44 => 
            array (
                'id' => 201,
                'title' => 'Blue/L',
                'price' => '60',
                'sale_price' => '50',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10105',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "L"}]',
                'product_id' => 164,
                'created_at' => '2021-05-09 11:11:19',
                'updated_at' => '2021-05-10 02:08:29',
            ),
            45 => 
            array (
                'id' => 202,
                'title' => 'Blue/S',
                'price' => '60',
                'sale_price' => '50',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10106',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 164,
                'created_at' => '2021-05-09 11:11:19',
                'updated_at' => '2021-05-10 02:08:29',
            ),
            46 => 
            array (
                'id' => 203,
                'title' => 'Blue/XL',
                'price' => '60',
                'sale_price' => '50',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10107',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 164,
                'created_at' => '2021-05-09 11:11:19',
                'updated_at' => '2021-05-10 02:08:29',
            ),
            47 => 
            array (
                'id' => 204,
                'title' => 'White/L',
                'price' => '60',
                'sale_price' => '50',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10108',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "L"}]',
                'product_id' => 164,
                'created_at' => '2021-05-09 11:11:19',
                'updated_at' => '2021-05-10 02:08:29',
            ),
            48 => 
            array (
                'id' => 205,
                'title' => 'White/S',
                'price' => '60',
                'sale_price' => '50',
                'quantity' => '600',
                'is_disable' => 0,
                'sku' => '10109',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "S"}]',
                'product_id' => 164,
                'created_at' => '2021-05-09 11:11:19',
                'updated_at' => '2021-05-10 02:08:29',
            ),
            49 => 
            array (
                'id' => 206,
                'title' => 'White/XL',
                'price' => '60',
                'sale_price' => '50',
                'quantity' => '300',
                'is_disable' => 0,
                'sku' => '10110',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 164,
                'created_at' => '2021-05-09 11:11:19',
                'updated_at' => '2021-05-10 02:08:29',
            ),
            50 => 
            array (
                'id' => 207,
                'title' => 'Blue/S',
                'price' => '50',
                'sale_price' => '45',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10115',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 165,
                'created_at' => '2021-05-09 11:12:37',
                'updated_at' => '2021-05-10 02:08:20',
            ),
            51 => 
            array (
                'id' => 208,
                'title' => 'Blue/M',
                'price' => '50',
                'sale_price' => '45',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10116',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 165,
                'created_at' => '2021-05-09 11:12:37',
                'updated_at' => '2021-05-10 02:08:20',
            ),
            52 => 
            array (
                'id' => 209,
                'title' => 'Blue/L',
                'price' => '50',
                'sale_price' => '45',
                'quantity' => '50',
                'is_disable' => 0,
                'sku' => '10117',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "L"}]',
                'product_id' => 165,
                'created_at' => '2021-05-09 11:12:37',
                'updated_at' => '2021-05-10 02:08:20',
            ),
            53 => 
            array (
                'id' => 210,
                'title' => 'Red/S',
                'price' => '50',
                'sale_price' => '45',
                'quantity' => '50',
                'is_disable' => 0,
                'sku' => '10118',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 165,
                'created_at' => '2021-05-09 11:12:37',
                'updated_at' => '2021-05-10 02:08:20',
            ),
            54 => 
            array (
                'id' => 211,
                'title' => 'Red/M',
                'price' => '50',
                'sale_price' => '45',
                'quantity' => '50',
                'is_disable' => 0,
                'sku' => '10119',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 165,
                'created_at' => '2021-05-09 11:12:37',
                'updated_at' => '2021-05-10 02:08:20',
            ),
            55 => 
            array (
                'id' => 212,
                'title' => 'Red/L',
                'price' => '50',
                'sale_price' => '45',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10120',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "L"}]',
                'product_id' => 165,
                'created_at' => '2021-05-09 11:12:37',
                'updated_at' => '2021-05-10 02:08:20',
            ),
            56 => 
            array (
                'id' => 213,
                'title' => 'Red/S',
                'price' => '90',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10122',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 166,
                'created_at' => '2021-05-09 11:13:25',
                'updated_at' => '2021-05-10 02:08:13',
            ),
            57 => 
            array (
                'id' => 214,
                'title' => 'Red/M',
                'price' => '90',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10123',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 166,
                'created_at' => '2021-05-09 11:13:25',
                'updated_at' => '2021-05-10 02:08:13',
            ),
            58 => 
            array (
                'id' => 215,
                'title' => 'Blue/S',
                'price' => '90',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10124',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 166,
                'created_at' => '2021-05-09 11:13:25',
                'updated_at' => '2021-05-10 02:08:13',
            ),
            59 => 
            array (
                'id' => 216,
                'title' => 'Blue/M',
                'price' => '90',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10125',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 166,
                'created_at' => '2021-05-09 11:13:25',
                'updated_at' => '2021-05-10 02:08:13',
            ),
            60 => 
            array (
                'id' => 217,
                'title' => 'Red/S',
                'price' => '40',
                'sale_price' => '35',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10130',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 167,
                'created_at' => '2021-05-09 11:18:59',
                'updated_at' => '2021-05-10 02:08:03',
            ),
            61 => 
            array (
                'id' => 218,
                'title' => 'Red/XL',
                'price' => '40',
                'sale_price' => '35',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10131',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 167,
                'created_at' => '2021-05-09 11:18:59',
                'updated_at' => '2021-05-10 02:08:03',
            ),
            62 => 
            array (
                'id' => 219,
                'title' => 'White/S',
                'price' => '40',
                'sale_price' => '35',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10132',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "S"}]',
                'product_id' => 167,
                'created_at' => '2021-05-09 11:18:59',
                'updated_at' => '2021-05-10 02:08:03',
            ),
            63 => 
            array (
                'id' => 220,
                'title' => 'White/XL',
                'price' => '40',
                'sale_price' => '35',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10134',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 167,
                'created_at' => '2021-05-09 11:18:59',
                'updated_at' => '2021-05-10 02:08:03',
            ),
            64 => 
            array (
                'id' => 221,
                'title' => 'Red/M',
                'price' => '50',
                'sale_price' => NULL,
                'quantity' => '100',
                'is_disable' => 0,
                'sku' => '10140',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 168,
                'created_at' => '2021-05-09 11:19:54',
                'updated_at' => '2021-05-10 02:07:55',
            ),
            65 => 
            array (
                'id' => 222,
                'title' => 'Red/L',
                'price' => '50',
                'sale_price' => NULL,
                'quantity' => '100',
                'is_disable' => 0,
                'sku' => '10141',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "L"}]',
                'product_id' => 168,
                'created_at' => '2021-05-09 11:19:54',
                'updated_at' => '2021-05-10 02:07:55',
            ),
            66 => 
            array (
                'id' => 223,
                'title' => 'Blue/M',
                'price' => '50',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '10142',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 168,
                'created_at' => '2021-05-09 11:19:54',
                'updated_at' => '2021-05-10 02:07:55',
            ),
            67 => 
            array (
                'id' => 224,
                'title' => 'Blue/L',
                'price' => '50',
                'sale_price' => NULL,
                'quantity' => '300',
                'is_disable' => 0,
                'sku' => '10143',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "L"}]',
                'product_id' => 168,
                'created_at' => '2021-05-09 11:19:54',
                'updated_at' => '2021-05-10 02:07:55',
            ),
            68 => 
            array (
                'id' => 225,
                'title' => 'Blue/M',
                'price' => '60',
                'sale_price' => '50',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10150',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 169,
                'created_at' => '2021-05-09 11:20:36',
                'updated_at' => '2021-05-10 02:07:46',
            ),
            69 => 
            array (
                'id' => 226,
                'title' => 'Blue/XL',
                'price' => '60',
                'sale_price' => '50',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10151',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 169,
                'created_at' => '2021-05-09 11:20:36',
                'updated_at' => '2021-05-10 02:07:46',
            ),
            70 => 
            array (
                'id' => 227,
                'title' => 'White/M',
                'price' => '60',
                'sale_price' => '50',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10152',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "M"}]',
                'product_id' => 169,
                'created_at' => '2021-05-09 11:20:36',
                'updated_at' => '2021-05-10 02:07:46',
            ),
            71 => 
            array (
                'id' => 228,
                'title' => 'White/XL',
                'price' => '60',
                'sale_price' => '50',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10153',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 169,
                'created_at' => '2021-05-09 11:20:36',
                'updated_at' => '2021-05-10 02:07:46',
            ),
            72 => 
            array (
                'id' => 229,
                'title' => 'Red/M',
                'price' => '60',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10160',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 170,
                'created_at' => '2021-05-09 11:21:14',
                'updated_at' => '2021-05-10 02:07:36',
            ),
            73 => 
            array (
                'id' => 230,
                'title' => 'Red/S',
                'price' => '60',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10161',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 170,
                'created_at' => '2021-05-09 11:21:14',
                'updated_at' => '2021-05-10 02:07:36',
            ),
            74 => 
            array (
                'id' => 231,
                'title' => 'Blue/M',
                'price' => '60',
                'sale_price' => NULL,
                'quantity' => '600',
                'is_disable' => 0,
                'sku' => '10162',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 170,
                'created_at' => '2021-05-09 11:21:14',
                'updated_at' => '2021-05-10 02:07:36',
            ),
            75 => 
            array (
                'id' => 232,
                'title' => 'Blue/S',
                'price' => '60',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10163',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 170,
                'created_at' => '2021-05-09 11:21:14',
                'updated_at' => '2021-05-10 02:07:36',
            ),
            76 => 
            array (
                'id' => 233,
                'title' => 'Blue/M',
                'price' => '40',
                'sale_price' => '35',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10170',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 171,
                'created_at' => '2021-05-09 11:22:00',
                'updated_at' => '2021-05-10 02:07:27',
            ),
            77 => 
            array (
                'id' => 234,
                'title' => 'Blue/L',
                'price' => '40',
                'sale_price' => '35',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10171',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "L"}]',
                'product_id' => 171,
                'created_at' => '2021-05-09 11:22:00',
                'updated_at' => '2021-05-10 02:07:27',
            ),
            78 => 
            array (
                'id' => 235,
                'title' => 'White/M',
                'price' => '40',
                'sale_price' => '35',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10172',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "M"}]',
                'product_id' => 171,
                'created_at' => '2021-05-09 11:22:00',
                'updated_at' => '2021-05-10 02:07:27',
            ),
            79 => 
            array (
                'id' => 236,
                'title' => 'White/L',
                'price' => '40',
                'sale_price' => '35',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10174',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "L"}]',
                'product_id' => 171,
                'created_at' => '2021-05-09 11:22:00',
                'updated_at' => '2021-05-10 02:07:27',
            ),
            80 => 
            array (
                'id' => 237,
                'title' => 'Red/S',
                'price' => '75',
                'sale_price' => NULL,
                'quantity' => '750',
                'is_disable' => 0,
                'sku' => '10175',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 172,
                'created_at' => '2021-05-09 11:22:47',
                'updated_at' => '2021-05-10 02:07:20',
            ),
            81 => 
            array (
                'id' => 238,
                'title' => 'Red/M',
                'price' => '75',
                'sale_price' => '10',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10176',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 172,
                'created_at' => '2021-05-09 11:22:47',
                'updated_at' => '2021-05-10 02:07:20',
            ),
            82 => 
            array (
                'id' => 239,
                'title' => 'Red/L',
                'price' => '75',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10177',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "L"}]',
                'product_id' => 172,
                'created_at' => '2021-05-09 11:22:47',
                'updated_at' => '2021-05-10 02:07:20',
            ),
            83 => 
            array (
                'id' => 240,
                'title' => 'Red/XL',
                'price' => '75',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10178',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 172,
                'created_at' => '2021-05-09 11:22:47',
                'updated_at' => '2021-05-10 02:07:20',
            ),
            84 => 
            array (
                'id' => 241,
                'title' => 'Red/S',
                'price' => '80',
                'sale_price' => '70',
                'quantity' => '800',
                'is_disable' => 0,
                'sku' => '10180',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 162,
                'created_at' => '2021-05-09 11:23:51',
                'updated_at' => '2021-05-10 02:08:51',
            ),
            85 => 
            array (
                'id' => 242,
                'title' => 'Red/M',
                'price' => '80',
                'sale_price' => '70',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10181',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 162,
                'created_at' => '2021-05-09 11:23:51',
                'updated_at' => '2021-05-10 02:08:51',
            ),
            86 => 
            array (
                'id' => 243,
                'title' => 'Blue/S',
                'price' => '80',
                'sale_price' => '70',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10182',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 162,
                'created_at' => '2021-05-09 11:23:51',
                'updated_at' => '2021-05-10 02:08:51',
            ),
            87 => 
            array (
                'id' => 244,
                'title' => 'Blue/M',
                'price' => '80',
                'sale_price' => '70',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10183',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 162,
                'created_at' => '2021-05-09 11:23:51',
                'updated_at' => '2021-05-10 02:08:51',
            ),
            88 => 
            array (
                'id' => 245,
                'title' => 'White/S',
                'price' => '80',
                'sale_price' => '70',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10184',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "S"}]',
                'product_id' => 162,
                'created_at' => '2021-05-09 11:23:51',
                'updated_at' => '2021-05-10 02:08:51',
            ),
            89 => 
            array (
                'id' => 246,
                'title' => 'White/M',
                'price' => '80',
                'sale_price' => '70',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '10185',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "M"}]',
                'product_id' => 162,
                'created_at' => '2021-05-09 11:23:51',
                'updated_at' => '2021-05-10 02:08:51',
            ),
            90 => 
            array (
                'id' => 247,
                'title' => 'Red/S',
                'price' => '35',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200101',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 110,
                'created_at' => '2021-05-10 02:11:22',
                'updated_at' => '2021-05-10 02:11:22',
            ),
            91 => 
            array (
                'id' => 248,
                'title' => 'Red/M',
                'price' => '35',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200102',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 110,
                'created_at' => '2021-05-10 02:11:22',
                'updated_at' => '2021-05-10 02:11:22',
            ),
            92 => 
            array (
                'id' => 249,
                'title' => 'Red/L',
                'price' => '35',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200103',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "L"}]',
                'product_id' => 110,
                'created_at' => '2021-05-10 02:11:22',
                'updated_at' => '2021-05-10 02:11:22',
            ),
            93 => 
            array (
                'id' => 250,
                'title' => 'Red/XL',
                'price' => '35',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200103',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 110,
                'created_at' => '2021-05-10 02:11:22',
                'updated_at' => '2021-05-10 02:11:22',
            ),
            94 => 
            array (
                'id' => 251,
                'title' => 'Blue/S',
                'price' => '35',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200104',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 110,
                'created_at' => '2021-05-10 02:11:22',
                'updated_at' => '2021-05-10 02:11:22',
            ),
            95 => 
            array (
                'id' => 252,
                'title' => 'Blue/M',
                'price' => '35',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200105',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 110,
                'created_at' => '2021-05-10 02:11:22',
                'updated_at' => '2021-05-10 02:11:22',
            ),
            96 => 
            array (
                'id' => 253,
                'title' => 'Blue/L',
                'price' => '35',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200106',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "L"}]',
                'product_id' => 110,
                'created_at' => '2021-05-10 02:11:22',
                'updated_at' => '2021-05-10 02:11:22',
            ),
            97 => 
            array (
                'id' => 254,
                'title' => 'Blue/XL',
                'price' => '35',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200107',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 110,
                'created_at' => '2021-05-10 02:11:22',
                'updated_at' => '2021-05-10 02:11:22',
            ),
            98 => 
            array (
                'id' => 255,
                'title' => 'Red/S',
                'price' => '80',
                'sale_price' => '70',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200120',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 111,
                'created_at' => '2021-05-10 02:12:37',
                'updated_at' => '2021-05-10 02:12:37',
            ),
            99 => 
            array (
                'id' => 256,
                'title' => 'Red/M',
                'price' => '80',
                'sale_price' => '70',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200121',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 111,
                'created_at' => '2021-05-10 02:12:37',
                'updated_at' => '2021-05-10 02:12:37',
            ),
            100 => 
            array (
                'id' => 257,
                'title' => 'Red/L',
                'price' => '80',
                'sale_price' => '70',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200122',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "L"}]',
                'product_id' => 111,
                'created_at' => '2021-05-10 02:12:37',
                'updated_at' => '2021-05-10 02:12:37',
            ),
            101 => 
            array (
                'id' => 258,
                'title' => 'Blue/S',
                'price' => '80',
                'sale_price' => '70',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200123',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 111,
                'created_at' => '2021-05-10 02:12:37',
                'updated_at' => '2021-05-10 02:12:37',
            ),
            102 => 
            array (
                'id' => 259,
                'title' => 'Blue/M',
                'price' => '81',
                'sale_price' => '70',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200124',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 111,
                'created_at' => '2021-05-10 02:12:37',
                'updated_at' => '2021-05-10 02:12:37',
            ),
            103 => 
            array (
                'id' => 260,
                'title' => 'Blue/L',
                'price' => '80',
                'sale_price' => '70',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200125',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "L"}]',
                'product_id' => 111,
                'created_at' => '2021-05-10 02:12:37',
                'updated_at' => '2021-05-10 02:12:37',
            ),
            104 => 
            array (
                'id' => 261,
                'title' => 'Blue/M',
                'price' => '120',
                'sale_price' => '100',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200130',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 113,
                'created_at' => '2021-05-10 02:14:04',
                'updated_at' => '2021-05-10 02:14:04',
            ),
            105 => 
            array (
                'id' => 262,
                'title' => 'Blue/L',
                'price' => '120',
                'sale_price' => '100',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200131',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "L"}]',
                'product_id' => 113,
                'created_at' => '2021-05-10 02:14:04',
                'updated_at' => '2021-05-10 02:14:04',
            ),
            106 => 
            array (
                'id' => 263,
                'title' => 'Blue/XL',
                'price' => '120',
                'sale_price' => '100',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200132',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 113,
                'created_at' => '2021-05-10 02:14:04',
                'updated_at' => '2021-05-10 02:14:04',
            ),
            107 => 
            array (
                'id' => 264,
                'title' => 'White/M',
                'price' => '120',
                'sale_price' => NULL,
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200135',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "M"}]',
                'product_id' => 113,
                'created_at' => '2021-05-10 02:14:04',
                'updated_at' => '2021-05-10 02:14:04',
            ),
            108 => 
            array (
                'id' => 265,
                'title' => 'White/L',
                'price' => '120',
                'sale_price' => '100',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200136',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "L"}]',
                'product_id' => 113,
                'created_at' => '2021-05-10 02:14:04',
                'updated_at' => '2021-05-10 02:14:04',
            ),
            109 => 
            array (
                'id' => 266,
                'title' => 'White/XL',
                'price' => '120',
                'sale_price' => '100',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200138',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 113,
                'created_at' => '2021-05-10 02:14:04',
                'updated_at' => '2021-05-10 02:14:04',
            ),
            110 => 
            array (
                'id' => 267,
                'title' => 'Red/S',
                'price' => '140',
                'sale_price' => '130',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '200140',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 114,
                'created_at' => '2021-05-10 02:15:47',
                'updated_at' => '2021-05-10 02:15:47',
            ),
            111 => 
            array (
                'id' => 268,
                'title' => 'Red/M',
                'price' => '140',
                'sale_price' => '130',
                'quantity' => '100',
                'is_disable' => 0,
                'sku' => '200141',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 114,
                'created_at' => '2021-05-10 02:15:47',
                'updated_at' => '2021-05-10 02:15:47',
            ),
            112 => 
            array (
                'id' => 269,
                'title' => 'Blue/S',
                'price' => '140',
                'sale_price' => '130',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200142',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 114,
                'created_at' => '2021-05-10 02:15:47',
                'updated_at' => '2021-05-10 02:15:47',
            ),
            113 => 
            array (
                'id' => 270,
                'title' => 'Blue/M',
                'price' => '140',
                'sale_price' => '130',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '200143',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 114,
                'created_at' => '2021-05-10 02:15:47',
                'updated_at' => '2021-05-10 02:15:47',
            ),
            114 => 
            array (
                'id' => 271,
                'title' => 'White/S',
                'price' => '140',
                'sale_price' => '130',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '200144',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "S"}]',
                'product_id' => 114,
                'created_at' => '2021-05-10 02:15:47',
                'updated_at' => '2021-05-10 02:15:47',
            ),
            115 => 
            array (
                'id' => 272,
                'title' => 'White/M',
                'price' => '140',
                'sale_price' => '130',
                'quantity' => '500',
                'is_disable' => 0,
                'sku' => '200146',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "M"}]',
                'product_id' => 114,
                'created_at' => '2021-05-10 02:15:47',
                'updated_at' => '2021-05-10 02:15:47',
            ),
            116 => 
            array (
                'id' => 273,
                'title' => 'Blue/M',
                'price' => '199',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '200160',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 116,
                'created_at' => '2021-05-10 02:16:55',
                'updated_at' => '2021-05-10 02:16:55',
            ),
            117 => 
            array (
                'id' => 274,
                'title' => 'Blue/XL',
                'price' => '200',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '200161',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 116,
                'created_at' => '2021-05-10 02:16:55',
                'updated_at' => '2021-05-10 02:16:55',
            ),
            118 => 
            array (
                'id' => 275,
                'title' => 'White/M',
                'price' => '200',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '200162',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "M"}]',
                'product_id' => 116,
                'created_at' => '2021-05-10 02:16:55',
                'updated_at' => '2021-05-10 02:16:55',
            ),
            119 => 
            array (
                'id' => 276,
                'title' => 'White/XL',
                'price' => '200',
                'sale_price' => NULL,
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '200164',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "XL"}]',
                'product_id' => 116,
                'created_at' => '2021-05-10 02:16:55',
                'updated_at' => '2021-05-10 02:16:55',
            ),
            120 => 
            array (
                'id' => 277,
                'title' => 'Red/S',
                'price' => '200',
                'sale_price' => '180',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '200170',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 130,
                'created_at' => '2021-05-10 02:21:38',
                'updated_at' => '2021-05-10 02:21:38',
            ),
            121 => 
            array (
                'id' => 278,
                'title' => 'Red/M',
                'price' => '200',
                'sale_price' => '180',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '200171',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 130,
                'created_at' => '2021-05-10 02:21:38',
                'updated_at' => '2021-05-10 02:21:38',
            ),
            122 => 
            array (
                'id' => 279,
                'title' => 'Blue/S',
                'price' => '200',
                'sale_price' => '180',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '200172',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 130,
                'created_at' => '2021-05-10 02:21:38',
                'updated_at' => '2021-05-10 02:21:38',
            ),
            123 => 
            array (
                'id' => 280,
                'title' => 'Blue/M',
                'price' => '200',
                'sale_price' => '180',
                'quantity' => '200',
                'is_disable' => 0,
                'sku' => '200173',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 130,
                'created_at' => '2021-05-10 02:21:38',
                'updated_at' => '2021-05-10 02:21:38',
            ),
            124 => 
            array (
                'id' => 281,
                'title' => 'Red/M',
                'price' => '150',
                'sale_price' => NULL,
                'quantity' => '150',
                'is_disable' => 0,
                'sku' => '150150',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 128,
                'created_at' => '2021-05-10 02:22:31',
                'updated_at' => '2021-05-10 02:22:31',
            ),
            125 => 
            array (
                'id' => 282,
                'title' => 'Red/L',
                'price' => '150',
                'sale_price' => NULL,
                'quantity' => '150',
                'is_disable' => 0,
                'sku' => '150151',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "L"}]',
                'product_id' => 128,
                'created_at' => '2021-05-10 02:22:31',
                'updated_at' => '2021-05-10 02:22:31',
            ),
            126 => 
            array (
                'id' => 283,
                'title' => 'Blue/M',
                'price' => '150',
                'sale_price' => NULL,
                'quantity' => '150',
                'is_disable' => 0,
                'sku' => '15015',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 128,
                'created_at' => '2021-05-10 02:22:31',
                'updated_at' => '2021-05-10 02:22:31',
            ),
            127 => 
            array (
                'id' => 284,
                'title' => 'Blue/L',
                'price' => '150',
                'sale_price' => NULL,
                'quantity' => '150',
                'is_disable' => 0,
                'sku' => '150153',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "L"}]',
                'product_id' => 128,
                'created_at' => '2021-05-10 02:22:31',
                'updated_at' => '2021-05-10 02:22:31',
            ),
            128 => 
            array (
                'id' => 285,
                'title' => 'Red/S',
                'price' => '200',
                'sale_price' => '150',
                'quantity' => '150',
                'is_disable' => 0,
                'sku' => '150160',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 126,
                'created_at' => '2021-05-10 02:23:29',
                'updated_at' => '2021-05-10 02:23:29',
            ),
            129 => 
            array (
                'id' => 286,
                'title' => 'Red/M',
                'price' => '200',
                'sale_price' => '150',
                'quantity' => '150',
                'is_disable' => 0,
                'sku' => '150161',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 126,
                'created_at' => '2021-05-10 02:23:29',
                'updated_at' => '2021-05-10 02:23:29',
            ),
            130 => 
            array (
                'id' => 287,
                'title' => 'White/S',
                'price' => '200',
                'sale_price' => '150',
                'quantity' => '150',
                'is_disable' => 0,
                'sku' => '150162',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "S"}]',
                'product_id' => 126,
                'created_at' => '2021-05-10 02:23:29',
                'updated_at' => '2021-05-10 02:23:29',
            ),
            131 => 
            array (
                'id' => 288,
                'title' => 'White/M',
                'price' => '200',
                'sale_price' => '150',
                'quantity' => '150',
                'is_disable' => 0,
                'sku' => '150140',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "M"}]',
                'product_id' => 126,
                'created_at' => '2021-05-10 02:23:29',
                'updated_at' => '2021-05-10 02:23:29',
            ),
            132 => 
            array (
                'id' => 289,
                'title' => 'Red/S',
                'price' => '125',
                'sale_price' => NULL,
                'quantity' => '125',
                'is_disable' => 0,
                'sku' => '125125',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 124,
                'created_at' => '2021-05-10 02:24:10',
                'updated_at' => '2021-05-10 02:24:10',
            ),
            133 => 
            array (
                'id' => 290,
                'title' => 'Red/M',
                'price' => '124',
                'sale_price' => NULL,
                'quantity' => '125',
                'is_disable' => 0,
                'sku' => '125125125',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 124,
                'created_at' => '2021-05-10 02:24:10',
                'updated_at' => '2021-05-10 02:24:10',
            ),
            134 => 
            array (
                'id' => 291,
                'title' => 'Red/L',
                'price' => '125',
                'sale_price' => NULL,
                'quantity' => '125',
                'is_disable' => 0,
                'sku' => '125125125125',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "L"}]',
                'product_id' => 124,
                'created_at' => '2021-05-10 02:24:10',
                'updated_at' => '2021-05-10 02:24:10',
            ),
            135 => 
            array (
                'id' => 292,
                'title' => 'Blue/S',
                'price' => '250',
                'sale_price' => '220',
                'quantity' => '220',
                'is_disable' => 0,
                'sku' => '220221',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 117,
                'created_at' => '2021-05-10 02:25:08',
                'updated_at' => '2021-05-10 02:25:08',
            ),
            136 => 
            array (
                'id' => 293,
                'title' => 'Blue/M',
                'price' => '250',
                'sale_price' => '220',
                'quantity' => '220',
                'is_disable' => 0,
                'sku' => '220220220',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 117,
                'created_at' => '2021-05-10 02:25:08',
                'updated_at' => '2021-05-10 02:25:08',
            ),
            137 => 
            array (
                'id' => 294,
                'title' => 'White/S',
                'price' => '250',
                'sale_price' => '220',
                'quantity' => '220',
                'is_disable' => 0,
                'sku' => '220220220220',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "S"}]',
                'product_id' => 117,
                'created_at' => '2021-05-10 02:25:08',
                'updated_at' => '2021-05-10 02:25:08',
            ),
            138 => 
            array (
                'id' => 295,
                'title' => 'White/M',
                'price' => '250',
                'sale_price' => '220',
                'quantity' => '220',
                'is_disable' => 0,
                'sku' => '220220220220220',
                'options' => '[{"name": "Color", "value": "White"}, {"name": "Size", "value": "M"}]',
                'product_id' => 117,
                'created_at' => '2021-05-10 02:25:08',
                'updated_at' => '2021-05-10 02:25:08',
            ),
            139 => 
            array (
                'id' => 296,
                'title' => 'Red/S',
                'price' => '300',
                'sale_price' => '250',
                'quantity' => '250',
                'is_disable' => 0,
                'sku' => '250250250250',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 118,
                'created_at' => '2021-05-10 02:26:06',
                'updated_at' => '2021-05-10 02:26:06',
            ),
            140 => 
            array (
                'id' => 297,
                'title' => 'Red/L',
                'price' => '300',
                'sale_price' => '250',
                'quantity' => '250',
                'is_disable' => 0,
                'sku' => '250250255',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "L"}]',
                'product_id' => 118,
                'created_at' => '2021-05-10 02:26:06',
                'updated_at' => '2021-05-10 02:26:06',
            ),
            141 => 
            array (
                'id' => 298,
                'title' => 'Blue/S',
                'price' => '300',
                'sale_price' => '250',
                'quantity' => '250',
                'is_disable' => 0,
                'sku' => '250250256',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 118,
                'created_at' => '2021-05-10 02:26:06',
                'updated_at' => '2021-05-10 02:26:06',
            ),
            142 => 
            array (
                'id' => 299,
                'title' => 'Blue/L',
                'price' => '300',
                'sale_price' => '250',
                'quantity' => '250',
                'is_disable' => 0,
                'sku' => '250250250250250250',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "L"}]',
                'product_id' => 118,
                'created_at' => '2021-05-10 02:26:06',
                'updated_at' => '2021-05-10 02:26:06',
            ),
            143 => 
            array (
                'id' => 304,
                'title' => 'Red/S',
                'price' => '260',
                'sale_price' => NULL,
                'quantity' => '260',
                'is_disable' => 0,
                'sku' => '260260',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "S"}]',
                'product_id' => 119,
                'created_at' => '2021-05-10 02:28:14',
                'updated_at' => '2021-05-10 02:28:14',
            ),
            144 => 
            array (
                'id' => 305,
                'title' => 'Red/M',
                'price' => '260',
                'sale_price' => NULL,
                'quantity' => '260',
                'is_disable' => 0,
                'sku' => '260260260',
                'options' => '[{"name": "Color", "value": "Red"}, {"name": "Size", "value": "M"}]',
                'product_id' => 119,
                'created_at' => '2021-05-10 02:28:14',
                'updated_at' => '2021-05-10 02:28:14',
            ),
            145 => 
            array (
                'id' => 306,
                'title' => 'Blue/S',
                'price' => '260',
                'sale_price' => NULL,
                'quantity' => '260',
                'is_disable' => 0,
                'sku' => '260260260',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "S"}]',
                'product_id' => 119,
                'created_at' => '2021-05-10 02:28:14',
                'updated_at' => '2021-05-10 02:28:14',
            ),
            146 => 
            array (
                'id' => 307,
                'title' => 'Blue/M',
                'price' => '260',
                'sale_price' => NULL,
                'quantity' => '260',
                'is_disable' => 0,
                'sku' => '260260260',
                'options' => '[{"name": "Color", "value": "Blue"}, {"name": "Size", "value": "M"}]',
                'product_id' => 119,
                'created_at' => '2021-05-10 02:28:14',
                'updated_at' => '2021-05-10 02:28:14',
            ),
        ));
        
        
    }
}